### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by raghuramlytcone** [zhou13/arcsim#1]
Hi Zhou, 
I tried installing the original arc sim from the website , was getting errors with taucs library.
When I cloned your repo 

cd dependencies/
make 

there was no error with taucs library atleast , but when I do the main make I was getting this error 

g++: error: unrecognized command line option ‘-std=c++14’

please help me out with this error. 

I am curious to know what problem statement are you working on ?

**Comment by zhou13** [comment]
Hi raghuramlytcone,

This repository currently is my own playground.  You'd better not use it as I may change things arbitrarily and I will not provide support for it.

The error indicates that your compiler (gcc) does not support C++14. You could tried to upgrade to gcc>5.0.  But again, this may not work.  I would suggest that you should try to make the original arcsim+taucs compile for your platform rather than using this repository.
